org: welene
service: cloud-backend

provider:
    name: aws
    runtime: nodejs22.x
    region: eu-north-1
    httpApi:
        cors:
            allowedOrigins:
                - '*'
            allowedHeaders:
                - Content-Type
                - Authorization # auth token must be in header in the call
            allowedMethods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
    iam:
        role: arn:aws:iam::405474549497:role/BasicLambdaRole
        # role that could potentially, maybe, have one or ten policies more than needed
    environment:
        JWT_TOKEN: supersecretkey

# etter hvert som jeg lager functions -- så lager jeg api-pathen til dem her
functions:
    handleRegister:
        handler: functions/handleRegister.handler
        events:
            - httpApi:
                  path: /register
                  method: POST
    handleLogin:
        handler: functions/handleLogin.handler
        events:
            - httpApi:
                  path: /login
                  method: POST
    getUserPosts:
        handler: functions/getUserPosts.handler
        events:
            - httpApi:
                  path: /posts/{userId}
                  method: GET
