org: welene
service: cloud-backend

provider:
    name: aws
    runtime: nodejs22.x
    region: eu-north-1
    iam:
        role: arn:aws:iam::405474549497:role/BasicLambdaRole
        # role that could potentially, maybe, have one or ten policies more than needed

# etter hvert som jeg lager functions -- så lager jeg api-pathen til dem her
functions:
    handleRegister:
        handler: functions/handleRegister.handler
        events:
            - http:
                  path: register
                  method: POST
