org: welene
service: cloud-backend

provider:
    name: aws
    runtime: nodejs18.x
    region: eu-north-1
    iam:
        role: Iamadmin
        # er det rett? ^

# etter hvert som jeg lager functions -- så lager jeg api-pathen til dem her
functions:
    hello:
        handler: handler.hello
        events:
            - http:
                  path: hello
                  method: get
